### ISSUE TITLE
[Performance] The UI freezes when producing the first visualisation

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-victory#18]
Why does the UI currently take forever to produce the first visualisation?  After that it is very fast.  I suspect you create *all* possible visualisations at that point and fill the cache?  I don't think this is necessary, i.e., I would only fill the cache lazily.  This way you pay a bit every time you visualise a match the first time, and nothing at all the next time (as the cache is used to retrieve the picture).

**Comment by anthonyanjorin** [comment]
> The UI already creates visualisations in a lazy fashion, i.e. only once it is actually required.

The question here is does it create _all_ diagrams the first time a single diagram is requested?  This seems to be the case as the first diagram takes a while, and then all other diagrams after that are super fast.  I seem to be the only one with this problem, however, perhaps it is a class loading problem...

If no one else comments here for a while I figure we can close this issue and forget it.

**Comment by LegionaryCohort** [comment]
No, the UI will only ever create visualisations on-demand, it doesn't attempt to fill the cache with pre-calculated visualisations.
The caching only provides a speed-up when the user selects a visualisable element more than once without changing any user options in between selections.

I am experiencing this issue too, so it doesn't seem to be system-dependent. I suspect that PlantUML requires some "warm-up" before generating its first image. Or it could be a class-loading thing, like you mentioned.

In any case, I currently see this as a low-prio issue, since it's only a little annoying and there are more pressing matters to work on at this time.
