### ISSUE TITLE
[Brainstorming] Work out a vision and requirements for breakpoints in Victory

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-victory#2]
We could use the next sprint meeting to discuss your presented vision for new features.

**Comment by Surbhi2111** [comment]
Hi, i would also like to highlight the other 2 ideas we presented in the last sprint meeting. 

1: Activating Matches for a certain Rule lets say for IgnoreInterNetworkFollowers.  
Idea: Instead of choosing several matches to reach this rule, Putting a button infront of every rule for breakpoint as shown in the image. So whenever the user wants to know the matches for a certain rule, as soon as the user chooses that button, all the rules which have match for that will activate. 
![2019-08-20 (1)](https://user-images.githubusercontent.com/45486012/63358662-b78e8b00-c36b-11e9-9687-7fb72bf3bdbd.png)

2: Presently there are many matches for a rule for eg. Basic Rule in the image, out of all these there are matches which are not matches for any other rule (and/or are empty i.e. donot yield/activate further any rule). We also get such matches for a leaf rule or ignore rules and this could be misleading for the user. 
Idea: Use breakpoints to limit the creation of such unwanted matches. and to have only those matches which are also the matches for all the other rules.
![2019-08-20 (2)](https://user-images.githubusercontent.com/45486012/63360229-48fefc80-c36e-11e9-9f5d-bc690f9e8123.png)
And regarding leaf rule or ignore rule : So if such kind of rule is activated there should be no matches under those rules as user might not know if these rule are actually leaf in the tree.

**Comment by anthonyanjorin** [comment]
Hi everyone,

Nils and I do not think it makes sense to start work on breakpoints considering our limited time.

This would make an excellent topic for a master thesis though (contact Nils) :)
