### ISSUE TITLE
[Victory] Improving the collapse/expand buttons

### ISSUE THREAD

**Issue by daryazarkalam** [eMoflon/emoflon-victory#24]
I think it would be better to have simply one toggle button to "expand/collapse" the rules and remove the "Collapse All" button as also previously discussed with Saman in the last sprint meeting.

**Comment by LegionaryCohort** [comment]
So what would this button do if the user has unfolded only a few nodes? Expand all or collapse all?

**Comment by daryazarkalam** [comment]
The same way both buttons are already designed and working. If the user wants to unfold/collapse a few rules, they can do it manually as they are doing now. Currently, there are two buttons "expand all" and "collapse all" which respectively expand and collapse "all" the rules. The suggestion is to simply remove one unnecessary button and make it a toggle button for the ease of use of the feature. The new button will expand/collapse all the rules.

**Comment by LegionaryCohort** [comment]
Yes, but which of the two options should happen when only some rules are expanded? Expand or collapse?

If no nodes are expanded then Expand All is the only sensible option, because all nodes are already collapsed. If all nodes are expanded, then Expand All does nothing, so Collapse All is the only sensible option. In these two cases it is clear which of the two possibilities the button should use.
But if there are some rules expanded and others not, then the button could either collapse all that are still expanded, or it could expand all that are still collapsed.
Which of the two options should be used here?

**Comment by LegionaryCohort** [comment]
Any answer to this?
Is this still relevant?

**Comment by anthonyanjorin** [comment]
Ok so my take on this is that it's a bit strange to have Expand and Collapse as buttons beside Apply.  Apply is like this *really* important button, and Expand/Collapse are more presentation-related.

Two "buttons" are required, however, so both Expand and Collapse -- I don't think it makes sense to try to reduce them to one.

My suggestion was to:

* Place the Expand/Collapse buttons in the top-right corner of the view (same as in all Eclipse views, I hope this is a JFace/SWT standard
* Use standard icons instead of a literal "Expand"/"Collapse" label.  The standard icons are are kind of stack of +s and -s (see Eclipse views)

Note that Eclipse views seems to only support Collapse and not Expand.

Could you check if there is a standard+easy way to do this?

**Comment by 09Ankita** [comment]
Merged with stable branch.
