### ISSUE TITLE
[Victory] Restart feature is not working 

### ISSUE THREAD

**Issue by Surbhi2111** [eMoflon/emoflon-victory#25]
the new feature to restart the debugger (by checking the Restart option and quiting debugger), which opens the debugger from the initial stage is not happening. 
The new window is not opening but the process in the console is still working, as shown in the image. this is the image for when i try to restart the debugger.
![2019-08-20](https://user-images.githubusercontent.com/45486012/63355820-10a7f000-c367-11e9-940b-227132fe8fef.png)

**Comment by LegionaryCohort** [comment]
In order to use the restart feature, you must let IBeX regenerate the Debug Operation Apps.

I.e. delete the Debug_Apps (or the entire debug package if you prefer) and rebuild the project. It will generate the new Debug_Apps that make use of the restart feature.

Please let me know if that works for you, or if the problem persists.

**Comment by Surbhi2111** [comment]
anhaann now it works
