### ISSUE TITLE
Reduce number of static methods in Victory

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-victory#34]
Static methods are typically a sign that something is wrong with an OO design.
The Victory class seems to be highly problematic:  all its methods are public and static :(  This basically means anything, anywhere can invoke these methods at anytime.  That's not good.

In general, I try hard to completely avoid static methods - they are really only useful in a few rare cases.

**Comment by LegionaryCohort** [comment]
The reasoning here is that Victory is a singleton.
The only real difference between a class with only static variables and members, and a regular class implemented with the Singleton pattern, is that the latter can be treated as a regular object while the former cannot. Since there is never a need for passing a Victory-object around, I opted for the static approach. I can change it to the Singleton approach, but it really doesn't make much of a difference.

The design-intention was to make it as simple as possible to invoke Victory from an adapter.
I can change it into a more OO approach, but that will inevitably lead to more objects being passed around, causing a bit of code bloat.

**Comment by anthonyanjorin** [comment]
My opinion is that Singleton is a nasty anti-pattern:  https://www.michaelsafyan.com/tech/design/patterns/singleton

Why can't there be multiple Victory instances?  Why should this be forbidden?  That doesn't mean that we need multiple instances, but there's a reason we're programming in Java and not C.

"Passing more objects around" is a good thing, because it forces you to design access and scope of your objects.  You can prevent anyone else from messing around with the object or invoking this or that method.  Using public and static just breaks this.  Your "methods" can be invoked from anywhere, by any other object, at any time :(

Public + static basically introduces global state to your program -- avoiding this is the reason OO was invented in the first place.  I wish (and I'm not alone) that Java did *not* have the static keyword.

**Comment by LegionaryCohort** [comment]
The idea was to reduce the amount of parameters that are being passed around. In my experience it makes it really difficult to understand what the point of a certain method is if it has tons of parameters that are all just injecting some access or dependency.

But fair enough, I can see the point of avoiding design patterns like this, I'll re-design it to conform more to typical OO ideas.

**Comment by LegionaryCohort** [comment]
I've adapted the logic to be more OO oriented.
All changes have been merged into the stable branches.
